#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

make html
PWD=`pwd`
PROJ_BASE=`basename "${PWD}"`
WWW_BASE="${HOME}/Sites"
PUBLISH_PATH="${WWW_BASE}/${PROJ_BASE}"
#echo "${PROJ_BASE}"
#echo "${PUBLISH_PATH}"

if [ ! -d "${PUBLISH_PATH}" ]; then
	mkdir -p "${PUBLISH_PATH}"
fi
cp -R * "${PUBLISH_PATH}"

