#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

make html
PWD=`pwd`
PROJ_BASE=`basename "${PWD}"`
cp -R * "~/Sites/${PROJ_BASE}"

